### ISSUE TITLE
lib folder is absent

### ISSUE THREAD

**Issue by apmeena** [populationtwo/ionic-todo#2]
@populationtwo  You have done a great job, I have run the commands and ionic todo app is running in my browser, but the **lib** folder does not exist in your sample project folder so it is not giving the proper look and feel. I am getting this errors in my web browser when I am running the command `ionic serve --lab`

![image](https://cloud.githubusercontent.com/assets/6169344/21089830/4a7f177e-c061-11e6-8d4d-bef3d6fd601b.png)

Thanks.

**Comment by populationtwo** [comment]
Hey @apmeena 

The assets might be missing. Try to run `bower install` and run `ionic serve' again.
Let me know if  the issue persist.

Cheers,

Edwin

**Comment by populationtwo** [comment]
Hey @apmeena 

Are you still experiencing this issue? I'm going to close this.
